# Generated by Django 5.0.6 on 2024-06-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_location_event_organizer_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='event_images/'),
        ),
    ]
